server:
  port: 8080
spring:
  application:
    name: proxy
    loadbalancer:
      ribbon:
        enabled: false
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
          filters:
            - StripPrefix=1
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/records/**
          filters:
            - StripPrefix=1
eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug